language: node_js
sudo: false
node_js:
- 8
install:
- npm install
script:
- npm run coverage
services:
- postgresql
before_script:
- psql -c 'create database testtelescopesdb;' -U postgres
- psql -c 'create database testobjectsdb;' -U postgres
- psql -c 'create database testvisibilitydb;' -U postgres
